version: "1"
jobs:
  backend-build:
    image: node:14
    steps:
      - name: Install backend dependencies
        working_directory: ../backend
        run: npm install
      - name: Start backend
        working_directory: ../backend
        run: node index.js
  frontend-build:
    image: node:14
    steps:
      - name: Install frontend dependencies
        working_directory: ./frontend
        run: npm install
      - name: Build frontend
        working_directory: ./frontend
        run: npm run build
      - name: Start frontend
        working_directory: ./frontend
        run: npm start
  deploy:
    image: cyclicci/deploy:latest
    environment:
      PGDATABASE: ${{ secrets.PGDATABASE }}
      PGUSER: ${{ secrets.PGUSER }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      PGHOST: ${{ secrets.PGHOST }}
      PGPORT: ${{ secrets.PGPORT }}
      DEV_PGDATABASE_URL: ${{ secrets.DEV_PGDATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      HASH_SALT_KEY: ${{ secrets.HASH_SALT_KEY }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}
      CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
    steps:
      - name: Deploy backend
        working_directory: ../backend
        run: |
          npm run migrate-up
          node index.js
      - name: Upload frontend assets to S3
        working_directory: ./frontend/build
        run: |
          aws s3 sync ./ s3://${{ secrets.AWS_S3_BUCKET_NAME }}/
